# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tickettime', models.DateTimeField(auto_now_add=True)),
                ('userid', models.IntegerField(default=0)),
                ('contains', models.CharField(blank=True, default='', max_length=999)),
            ],
            options={
                'ordering': ('tickettime',),
            },
        ),
    ]
